### ISSUE TITLE
[Drive] "Pose Jumped" Calculation doesen't work

### ISSUE THREAD

**Issue by GreenTomato5** [FRC-7525/CTRE-Swerve#1]
The math appears correct and as far as I can tell it is. The problem occurs when comparing last pose to current pose (It thinks it doesn't change when it clearly does. You can slightly remedy this by only running the code every however many loops however we should find out the root cause of why pose doesn't report to be changed 💯

**Comment by GreenTomato5** [comment]
how do you un-self assign

**Comment by PotmanNob** [comment]
resolved frfr
